# Generated by Django 4.0.dev20210401123330 on 2021-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(max_length=200, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
