# Generated by Django 4.0.dev20210401123330 on 2021-12-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_student_resume_alter_student_usn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
