# Generated by Django 4.0.dev20210401123330 on 2021-12-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='student',
            name='academics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='certificates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='clubs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extracurcular',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profiles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
