# Generated by Django 4.0.dev20210401123330 on 2021-12-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_remove_student_linkedin_student_academics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academics',
        ),
        migrations.AddField(
            model_name='student',
            name='Diploma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenthgrade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelvegrade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
