# Generated by Django 4.0.dev20210401123330 on 2021-12-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0008_student_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitute', models.FileField(blank=True, null=True, upload_to='amplitude/')),
                ('technical', models.FileField(blank=True, null=True, upload_to='technical/')),
                ('vandc', models.FileField(blank=True, null=True, upload_to='vandc/')),
                ('logicalresoning', models.FileField(blank=True, null=True, upload_to='logicalresoning/')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
