# Generated by Django 4.0.dev20210401123330 on 2021-12-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0009_resources_alter_student_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Internships',
            new_name='Internship',
        ),
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
