# Generated by Django 4.0.dev20210401123330 on 2021-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0010_rename_internships_internship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=models.CharField(max_length=200, null=True), max_length=200),
        ),
    ]
