# Generated by Django 4.0.dev20210401123330 on 2021-12-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0012_rename_extracurcular_student_extracurricular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
