# Generated by Django 4.0.dev20210401123330 on 2021-12-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0016_alter_student_branch_alter_student_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='internships',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placements.internship'),
        ),
    ]
