# Generated by Django 4.0.dev20210401123330 on 2021-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0021_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
