# Generated by Django 4.0.dev20210401123330 on 2021-12-18 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0023_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='certificates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1000, null=True), default=None, size=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1000, null=True), default=None, size=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='projectslinks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1000, null=True), default=None, size=20),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
