# Generated by Django 4.0.dev20210401123330 on 2021-12-29 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0028_alter_student_certificates_alter_student_profiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Instrumentation Engineering', 'Electronics and Instrumentation Engineering'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Industrial Engineering and Management', 'Industrial Engineering and Management'), ('Information Science and Engineering', 'Information Science and Engineering'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='certificates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, null=True, size=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='projectslinks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, null=True, size=20),
        ),
    ]
