# Generated by Django 4.0.dev20210401123330 on 2021-12-31 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0029_alter_student_branch_alter_student_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, null=True, size=None),
        ),
    ]
