# Generated by Django 4.0.dev20210401123330 on 2021-12-31 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0030_alter_student_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1000), default=list, size=None),
        ),
    ]
